FROM jenkins/jenkins:lts

USER root

# Install Docker CLI + AWS CLI
RUN apt-get update && \
    apt-get install -y docker.io unzip curl && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf awscliv2.zip aws

# Jenkins user ko docker group me dalo
RUN usermod -aG docker jenkins
\
]'[]'
USER jenkins
